/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Mon May  7 03:22:18 2018. */

#ifndef PB_POTENTIOMETER_POTENTIOMETER_PB_H_INCLUDED
#define PB_POTENTIOMETER_POTENTIOMETER_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Potentiometer_Brightness {
    int32_t id;
    int32_t level;
/* @@protoc_insertion_point(struct:Potentiometer_Brightness) */
} Potentiometer_Brightness;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Potentiometer_Brightness_init_default   {0, 0}
#define Potentiometer_Brightness_init_zero      {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Potentiometer_Brightness_id_tag          1
#define Potentiometer_Brightness_level_tag       2

/* Struct field encoding specification for nanopb */
extern const pb_field_t Potentiometer_Brightness_fields[3];

/* Maximum encoded size of messages (where known) */
#define Potentiometer_Brightness_size            22

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define POTENTIOMETER_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif

