/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Mon May  7 03:22:18 2018. */

#include "Potentiometer.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Potentiometer_Brightness_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, Potentiometer_Brightness, id, id, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, Potentiometer_Brightness, level, id, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */

